language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

stages:
  - development
  - production

staging:
  stage: development
  env:
    - REACT_APP_STAGE=development
  before_deploy:
    - yarn build
  deploy:
    skip_cleanup: true
    provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: "sagui-dev"
  branches:
    only:
      - feature/development

staging:
  stage: production
  before_deploy:
    - yarn build
  env:
    - REACT_APP_STAGE=production
  deploy:
    skip_cleanup: true
    provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: "sagui-app"
  branches:
    only:
      - master

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - contato@brunomacedo.com.br
