language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

before_deploy:
  - yarn build

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "sagui-app"

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - contato@brunomacedo.com.br
