language: node_js

node_js:
  - "8"

cache:
  directories:
    "node_modules"

before_install:
  - npm install

branches:
  only:
    - master

before_deploy:
  - npm run build
  - echo "Deploying..."

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN

notifications:
  email:
    on_success: never # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - contato@brunomacedo.com.br

jobs:
  include:
    - stage: test
      script: echo "Stage 1 Test 1"
    - stage: deploy
      script: echo "Stage 2 Test 2"
