language: node_js

node_js:
  - "8"

cache:
  directories:
    "node_modules"

before_install:
  - npm install

# install:
#   - npm install -g firebase-tools

before_script:
  - npm run build

script:
  - echo "Deploying..."

branches:
  only:
  - master

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN

notifications:
  email:
    on_success: never # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - contato@brunomacedo.com.br
