language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
env:
  - REACT_APP_STAGE=development
before_deploy:
  - yarn build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "sagui-dev"
  skip_cleanup: true
  on:
    branch:
      - feature/development
notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - contato@brunomacedo.com.br
