language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: development
      env:
        - REACT_APP_STAGE=development
      before_deploy:
        - yarn build
      deploy:
        skip_cleanup: true
        provider: firebase
        token:
          secure: $FIREBASE_TOKEN
        project: "sagui-dev"
        if: branch = feature/development

    - stage: production
      env:
        - REACT_APP_STAGE=production
      before_deploy:
        - yarn build
      deploy:
        skip_cleanup: true
        provider: firebase
        token:
          secure: $FIREBASE_TOKEN
        project: "sagui-app"
        if: branch = master

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - contato@brunomacedo.com.br
