language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules

before_deploy:
  - yarn build

deploy:
  - provider: firebase
    env:
      - REACT_APP_STAGE=development
    token:
      secure: $FIREBASE_TOKEN
    project: "sagui-dev"
    skip_cleanup: true
    on:
      branch:
        - feature/development

  - provider: firebase
    env:
      - REACT_APP_STAGE=production
    token:
      secure: $FIREBASE_TOKEN
    project: "sagui-app"
    skip_cleanup: true
    on:
      branch:
        - master

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - contato@brunomacedo.com.br
