language: node_js

node_js:
  - "8"

cache:
  directories:
    "node_modules"

before_install:
  - npm install

before_deploy:
  - npm run build
  - echo "Deploying..."

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN

branches:
  only:
    - master

notifications:
  email:
    on_success: never # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - contato@brunomacedo.com.br
