export const {
  REACT_APP_APIKEY,
  REACT_APP_AUTHDOMAIN,
  REACT_APP_DATABASEURL,
  REACT_APP_GA,
  REACT_APP_MESSAGINGSENDERID,
  REACT_APP_PROJECTID,
  REACT_APP_STAGE,
  REACT_APP_STORAGEBUCKET,
} = process.env;

export const env = {
  REACT_APP_APIKEY,
  REACT_APP_AUTHDOMAIN,
  REACT_APP_DATABASEURL,
  REACT_APP_GA,
  REACT_APP_MESSAGINGSENDERID,
  REACT_APP_PROJECTID,
  REACT_APP_STAGE,
  REACT_APP_STORAGEBUCKET,
};
